---
title: "Admin essentials when starting out"
format: html
editor: source
engine: knitr
---

<!--- below block is for justifying text --->
```{css, echo = FALSE}
.justify {
  text-align: justify
}
```

::: {.justify}

## Registration

Your first step after moving to Mainz will be to complete your **registration with the city**. You can book an appointment for registration online at [this link](https://mainz.de/verwaltung-und-politik/buergerservice-online/termine-online.php), and it is wise to book an appointment ASAP. You can even book an appointment before physically moving if you know when you will move. The university has provided some guidelines on booking an appointment [here](https://www.international-office.uni-mainz.de/files/2022/03/klickanleitung_buergerservice_foreignersoffice_combined.pdf). The appointment will be at the [Bürgeramt](https://www.mainz.de/vv/oe/buergeramt.php) (=citizenship office) in Mainz, located on [Kaiserstraße 3-5](https://www.google.com/maps/place/Einwohnermeldeamt+Mainz/@50.0025234,8.2605038,17z/data=!3m1!4b1!4m6!3m5!1s0x47bd93f7e6a89f29:0xc33c4d39eb0f4dcf!8m2!3d50.0025234!4d8.2605038!16s%2Fg%2F11b6tvc1tc?entry=ttu&g_ep=EgoyMDI1MDMxMS4wIKXMDSoJLDEwMjExNDU1SAFQAw%3D%3D).
<br>
To register, you will need to have

- Your passport (and a visa if applicable).
- A residence address to which mail can be sent. This will ideally be the place you intend to stay at for a prolonged period of time, but an AirBnB or similar is also okay as long as it has a post-box. If the latter, you will later need to inform the city when you relocate. See [here](https://www.iamexpat.de/housing/german-housing-market/change-of-address-germany) for how this is done.
 - Proof that you are indeed staying at the address mentioned above. If you are renting a place, you should ask your landlord/landlady for a [Wohnungsgeberbestätigung](https://www.mainz.de/vv/medien/internet/Wohnungsgebende-Bescheinigung-Formular.pdf).
- If you are married, a marriage certificate (officially translated into German)
- If you are registering children, you also need to carry ID proof for your children.

When you register, you will receive a piece of paper from the citizenship office called an *Anmeldebescheinigung* (=registration certificate). **Hold on to this certificate**, you could need it for many things. Most immediately, if you wish to open a German bank account, they will almost certainly ask you for your registration certificate. A week or two after registering, you will receive your *Steuer ID* (= tax ID) by post to the address you registered. This ID should be communicated to both JGU's HR contact and to Judith (our secretary). This is important because **you cannot be paid without a Steuer ID**.

## Certificate of Conduct

The certificate of conduct is a police document required by JGU that essentially checks whether you have a criminal record in your home country. Everyone with an employment contract **must** submit a Certificate of Conduct to the university within the first three months of starting. Like Registration, the Certificate of Conduct is obtained from the Bürgeramt. The Certificate requires a €13 fee (to be paid by card). The Burgeramt will send the certificate directly to JGU's HR: The address of HR is `Dezernat Personal, Forum universitatis 3, 550099 Mainz`. Both registration and getting the Certificate of Conduct can be done in the same appointment --- I recommend doing this to save yourself time, there is no point in booking two separate appointments.

## Bank accounts and getting your salary

You will be paid on the last working day of each month. To be paid, the university needs to have your Steuer ID. You also need to have a bank account that has an [IBAN](https://en.wikipedia.org/wiki/International_Bank_Account_Number). As far as I (Shikhara) am aware, this is a largely European concept, so if you are not from Europe, you will likely have to create a local bank account to be paid. You can open a bank account immediately after registering with the city (see above), though some banks may have more stringent requirements than others (for instance, Sparkasse sometimes requires long-term residence permits). See [here](https://www.how-to-germany.com/bank-accounts/) for some opinions on various banks in Germany to see your options. I (Shikhara) use Commerzbank because they have a branch in Mainz, have a very straightforward online process for opening an account, and offer English customer service. I have also heard good things about online banks like N26 and Revolut. However, please do your own research before taking financial advice on which bank to choose. Once you have an IBAN, you should share your IBAN with Sabine. This, again, is important for getting your salary.<br>
When you get your first payslip, you will be able to find the *Personalnummer* that has been given to you by the Landesamt für finanzen (LfF). The Personalnummer is an eight digit number assigned to you by the LfF and is important for tax purposes, so keep note of it. In general, if you contact the LfF for queries related to your salary, tax contributions, or tax returns, you will need to quote your Personalnummer. You should also hold on to all the payslips you receive because you could need them for administrative purposes (for instance, when applying for a residence permit, see below). You will also need your Personalnummer to get travel expenses reimbursed.

## Applying for a residence permit

If you are staying in Germany for longer than a year, you will need to apply for a *residence permit*. A residence permit essentially supersedes a visa and will be given for the length of your contract (or until your passport expires if that happens first). Applications for residence permits from JGU scientists are processed differently by the Bürgeramt, so do not try to apply for a residence permit independently. Instead, write an email to the JGU Welcome Center (`welcome[at]international[dot]uni[hyphen]mainz[dot]de`) saying you are employed with us and need a residence permit, and the Welcome Center will arrange for an appointment with the Burgerämt and give you further directions. When you first write to the Welcome Center for this, they will ask you to fill out some forms they send, and also send them copies of

- Your passport and visa
- Your rental certificate
- Your employment certiciate
- A [hosting agreement](https://www.bamf.de/SharedDocs/Anlagen/DE/Forschung/Forschungseinrichtungen/08muster-aufnahmevereinbarung-deutsch-englisch.pdf?__blob=publicationFile&v=13) from Hanna
- A health insurance certificate (*not* just a card)
- Your last three payslips


For the appointment with the Burgerämt itself, you will need

- A current (= at most six month old) biometric picture of yourself.
- Your passport and visa if applicable.
- A debit card to pay a fee of €100 (they don't take cash). I (Shikhara) was able to get this reimbursed by the university, so hang on to the receipt.

You will need to visit the Burgerämt in person a few weeks after this appoint to pick up your residence permit (the Burgerämt will give you an exact date). While your application is being processed (after the first appointment but before you pick it up), it is possible to ask the Burgerämt for a *Fiktionsbescheinigung*, a temporary form for any immigration/border authorities that says that your application is being processed. I would recommend taking this form just to be safe. The residence permit process can take a really long time, so make sure to contact the Welcome Center well before your visa expires. This is really important because **your contract will be terminated immediately by HR if you do not have a residence permit in hand before your visa expires**.

## Miscellaneous Germany things

- Most shops, and all supermarkets, are closed on Sundays in Germany. Plan for this so you don't starve.
- Germany lives in the stone age with respect to technology and still relies heavily on cash and post. Make sure to keep some cash on you (many shops and restaurants don't take card), and check your postbox often (a lot of the official communication happens via post).
- Public transport is very good in Germany, and Mainz is no exception. The [Deutschlandticket](https://en.wikipedia.org/wiki/Deutschlandticket) allows you to board any regional public transport (all buses and trams, and regional trains such as REs, RBs, U-Bahns, and S-Bahns) for just €58 per month. This is a fantastic deal, I strongly recommend you take it.
- [DeepL](https://www.deepl.com/en/translator) is a very good online translator for translating German to English and vice versa. They also have an app.
- You can buy a SIM card at most supermarkets, and they will be able to activate it for you at the checkout counter. You may need to provide some form of proof of identity such as a passport when activating the passport.
- Mainz has various weekly markets selling fresh produce. You can see the days, times, and locations of the markets [here](https://www.mainz.de/freizeit-und-sport/einkaufen-und-maerkte/stadtteilmaerkte.php#).
- [Kleinanzeigen](https://www.kleinanzeigen.de/) is a good website and app for buying various things such as furniture, clothes, and electronics second hand. Think of it as eBay but German.
- If you are looking for a place to stay, try [Immoscout](https://www.immobilienscout24.de/) and [Immowelt](https://www.immowelt.de/). If you are okay with shared housing, you can also look at [WG-Gesucht](https://www.wg-gesucht.de/). The housing market is really tough, so don't be surprised if you have a very hard time finding a place. Paying for the Immoscout premium service seems to help.
- [Toogoodtogo](https://www.toogoodtogo.com/en-us) is a great servic for buying food and groceries that are left unsold at the end of the day. It's really cheap, and helps reduce food waste!
- [NINA](https://www.bbk.bund.de/DE/Warnung-Vorsorge/Warn-App-NINA/warn-app-nina_node.html) is the official federal disaster warning app in Germany. Download it so you stay informed about any natural disasters (storms, fires, etc) in your area.
- [NORA](https://www.nora-notruf.de/en-en/startpage) is the official emergency call app in Germany, and will let you contact emergency services without speaking the language.
- [Meteoblue](https://play.google.com/store/apps/details?id=com.meteoblue.droid&hl=en) is a reasonably good weather app in Germany.
- If you enjoy hiking, consider using [komoot](https://www.komoot.com/) or [alltrails](https://www.alltrails.com/) to find hiking routes around you. Germany tends to have many well-documented routes, so the apps are a very good resource. The [Rheinsteig](https://www.rheinsteig.de/en/rheinsteig) is a long (320km) multi-stage hike from Bonn to Weisbaden that could be a good summer goal to keep you occupied on the weekends ;)

:::


