---
title: "General information"
format: html
editor: source
engine: knitr
---

Welcome to the JGU and our department! Sabine (our wonderful secretary) has gathered some useful Information for you. Please read through carefully.

## Information from the JGU for new employees

[Prepare for your arrival](https://newemployees.uni-mainz.de/new-employees/prepare-your-arrival/)

## Vacation

As an employee of the University, you have 30 days paid leave per year (on a full year’s contract). You must take this leave each year. Please use Gisbo, using the following link to submit your vacation request, which must be approved by your PI: https://arbeitszeit.uni-mainz.de/. In the settings, please fill in your PI’s email address as well as `sekretariat.oekologie@uni-mainz.de`.

## Sick leave

If you are sick and unable to come to work, please send an email to the following addresses so that we can register you in the Gisbo (time management software) system as ill: `iome_krankmeldung@uni-mainz.de`; `Sekretariat.oekologie@uni-mainz.de`; or your PI.

When you are healthy again, please send another email letting us know you are healthy and returning to work. Please note – if you are out due to illness for more than 3 days, you must provide a doctor’s note.

Further information about vacation, illness and other personnel issues can also be found on the [JGU HR Website](https://www.verwaltung.personal.uni-mainz.de/tarifbeschaeftigte/). Most of the info is in German, some in English.

## Travelling for University related activities

1.  Travel request: [download form](https://www.verwaltung.personal.uni-mainz.de/files/2023/02/DRA-Fachbereiche-english.xlsx) – please complete with a signature from Hanna as soon as you start planning your travels. Please be sure to submit it to Sabine, so she can forward it to the university management.

2.  If you are travelling within the EU you'll need to fill this out for insurance purposes: [download form](https://www.verwaltung.personal.uni-mainz.de/files/2019/12/Anlage-10-Einzelentsendeantrag-EU.pdf). This needs to be submitted prior to the trip, ideally alongside the travel request.

3.  Travel reimbursement: [download form](https://www.verwaltung.personal.uni-mainz.de/files/2021/10/RK-Antrag-10-2021-englisch.xls) – once you return from your trip, you will need to complete this form to request reimbursement for all travel expenses. Please submit this form, all original receipts and payment confirmation from your MC or Bank statement.


## Miscellaneous Germany things

- Most shops, and all supermarkets, are closed on Sundays in Germany. Plan for this so you don't starve.
- Germany lives in the stone age with respect to technology and still relies heavily on cash and post. Make sure to keep some cash on you (many shops and restaurants don't take card), and check your postbox often (a lot of the official communication happens via post).
- Public transport is very good in Germany, and Mainz is no exception. The [Deutschlandticket](https://en.wikipedia.org/wiki/Deutschlandticket) allows you to board any regional public transport (all buses and trams, and regional trains such as REs, RBs, U-Bahns, and S-Bahns) for just €58 per month. This is a fantastic deal, I strongly recommend you take it.
- [DeepL](https://www.deepl.com/en/translator) is a very good online translator for translating German to English and vice versa. They also have an app.
- You can buy a SIM card at most supermarkets, and they will be able to activate it for you at the checkout counter. You may need to provide some form of proof of identity such as a passport when activating the passport.
- Mainz has various weekly markets selling fresh produce. You can see the days, times, and locations of the markets [here](https://www.mainz.de/freizeit-und-sport/einkaufen-und-maerkte/stadtteilmaerkte.php#).
- [Kleinanzeigen](https://www.kleinanzeigen.de/) is a good website and app for buying various things such as furniture, clothes, and electronics second hand. Think of it as eBay but German.
- If you are looking for a place to stay, try [Immoscout](https://www.immobilienscout24.de/) and [Immowelt](https://www.immowelt.de/). If you are okay with shared housing, you can also look at [WG-Gesucht](https://www.wg-gesucht.de/). The housing market is really tough, so don't be surprised if you have a very hard time finding a place. Paying for the Immoscout premium service seems to help.
- [Toogoodtogo](https://www.toogoodtogo.com/en-us) is a great servic for buying food and groceries that are left unsold at the end of the day. It's really cheap, and helps reduce food waste!